### PR TITLE
Add approval-notes input

### LINKED ISSUE #10: Can a parameter be added to set the "Notes for certification"?
Simple FR, can a new parameter be added for setting the "Notes for certification" as described here (https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api?tabs=v1-1#publishing-the-submission).

Sometimes the Microsoft reviews are very particular about an extension update having these notes

### PR DESCRIPTION
**Pull request by jermowery**
Fixes #10 

Tried to make this as consistent with the firefox-addon repo as possible since it is essentially the same thing

### CODE REVIEW

**Comment by jermowery** [comment]
Ping on this

**Comment by wdzeng** [comment]
Sorry I am busy these days. Will soon take a look.

**Comment by jermowery** [comment]
Another friendly ping on this, it is currently causing me some trouble 🙂

**Comment by wdzeng** [comment]
😢😢

**Comment by wdzeng** [comment]
Thanks for the PR and I apologize for the so late response. Merged into the main branch. Please try v2.1.0.

I changed the input `approval-notes` to `notes-for-certification`, which is the name mentioned in the Microsoft Edge Add-on API docs. Since not all users are using both Firefox and Edge, I thought there is no need to align input names across these actions.

Also, the docs sometimes mentions the note should be of JSON format (`{ "notes": "foo" }`, your PR) [1], and sometimes it states it should be aplain text [2]. I am not sure which is correct. I tried the latter and it worked, so I adopted it.

[1]: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api?tabs=v1-1#sample-request-3
[2]: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference?tabs=v1-1#request-body-2

**Pull request closed without merging**
